version: '3.8'
services:
  kafka-ui-api:
    build: .
    environment:
      - PORT=3000
      - KAFKA_BROKERS=broker:9092
      - KAFKA_CLIENT_ID=kafka-ui
      - JWT_SECRET=dev-secret
    ports:
      - "3000:3000"
    depends_on:
      - broker
  zookeeper:
    image: bitnami/zookeeper:3.9
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
  broker:
    image: bitnami/kafka:3.6
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://broker:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
